"""create all 57 tables

Revision ID: 6c87c90c274e
Revises: 
Create Date: 2025-10-23 04:49:34.986377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c87c90c274e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_delay_set_events',
    sa.Column('old_activation_delay', sa.BigInteger(), nullable=False),
    sa.Column('new_activation_delay', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('burnable_eth_shares_increased_events',
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claimer_for_set_events',
    sa.Column('earner', sa.String(), nullable=False),
    sa.Column('old_claimer', sa.String(), nullable=False),
    sa.Column('claimer', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('default_operator_split_bips_set_events',
    sa.Column('old_default_operator_split_bips', sa.BigInteger(), nullable=False),
    sa.Column('new_default_operator_split_bips', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution_root_disabled_events',
    sa.Column('root_index', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution_root_submitted_events',
    sa.Column('root_index', sa.BigInteger(), nullable=False),
    sa.Column('root', sa.String(), nullable=False),
    sa.Column('rewards_calculation_end_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('activated_at', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pectra_fork_timestamp_set_events',
    sa.Column('new_pectra_fork_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proof_timestamp_setter_set_events',
    sa.Column('new_proof_timestamp_setter', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards_claimed_events',
    sa.Column('root', sa.String(), nullable=False),
    sa.Column('earner', sa.String(), nullable=False),
    sa.Column('claimer', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('claimed_amount', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards_for_all_submitter_set_events',
    sa.Column('rewards_for_all_submitter', sa.String(), nullable=False),
    sa.Column('old_value', sa.Boolean(), nullable=False),
    sa.Column('new_value', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards_updater_set_events',
    sa.Column('old_rewards_updater', sa.String(), nullable=False),
    sa.Column('new_rewards_updater', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stakers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_whitelister_changed_events',
    sa.Column('previous_address', sa.String(), nullable=False),
    sa.Column('new_address', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocation_delay_set_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('delay', sa.BigInteger(), nullable=False),
    sa.Column('effect_block', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avs_metadata_update_events',
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('metadata_uri', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avs_registrar_set_events',
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('registrar', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beacon_chain_eth_withdrawal_completed_events',
    sa.Column('pod_owner_id', sa.String(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('nonce', sa.BigInteger(), nullable=False),
    sa.Column('delegated_address', sa.String(), nullable=False),
    sa.Column('withdrawer', sa.String(), nullable=False),
    sa.Column('withdrawal_root', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pod_owner_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beacon_chain_slashing_events',
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('prev_beacon_chain_slashing_factor', sa.BigInteger(), nullable=False),
    sa.Column('new_beacon_chain_slashing_factor', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('burnable_shares_decreased_events',
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delegation_approver_updated_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('new_delegation_approver', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit_events',
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit_scaling_factor_updated_events',
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('new_deposit_scaling_factor', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eigen_pods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encumbered_magnitude_updated_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('encumbered_magnitude', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('max_magnitude_updated_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('max_magnitude', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_avs_registration_status_updated_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'UNREGISTERED', name='avsregistrationstatus'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_avs_split_bips_set_events',
    sa.Column('caller', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('activated_at', sa.BigInteger(), nullable=False),
    sa.Column('old_operator_avs_split_bips', sa.BigInteger(), nullable=False),
    sa.Column('new_operator_avs_split_bips', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_directed_avs_rewards_submission_events',
    sa.Column('caller', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('operator_directed_rewards_submission_hash', sa.String(), nullable=False),
    sa.Column('submission_nonce', sa.BigInteger(), nullable=False),
    sa.Column('strategies_and_multipliers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('operator_rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_metadata_update_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('metadata_uri', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_pi_split_bips_set_events',
    sa.Column('caller', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('activated_at', sa.BigInteger(), nullable=False),
    sa.Column('old_operator_pi_split_bips', sa.BigInteger(), nullable=False),
    sa.Column('new_operator_pi_split_bips', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_registered_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('delegation_approver', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_share_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('INCREASED', 'DECREASED', name='shareeventtype'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_shares_slashed_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('total_slashed_shares', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards_submission_events',
    sa.Column('avs_id', sa.String(), nullable=True),
    sa.Column('submitter', sa.String(), nullable=False),
    sa.Column('submission_nonce', sa.BigInteger(), nullable=False),
    sa.Column('rewards_submission_hash', sa.String(), nullable=False),
    sa.Column('submission_type', sa.Enum('AVS_REWARDS', 'REWARDS_FOR_ALL', 'REWARDS_FOR_ALL_EARNERS', 'OPERATOR_DIRECTED_AVS', 'OPERATOR_DIRECTED_OPERATOR_SET', name='rewardssubmissiontype'), nullable=False),
    sa.Column('strategies_and_multipliers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('start_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staker_delegation_events',
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('delegation_type', sa.Enum('DELEGATED', 'UNDELEGATED', 'FORCE_UNDELEGATED', name='delegationtype'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staker_force_undelegated_events',
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_whitelist_events',
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('ADDED', 'REMOVED', name='strategywhitelisteventtype'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawal_events',
    sa.Column('withdrawal_root', sa.String(), nullable=False),
    sa.Column('staker_id', sa.String(), nullable=False),
    sa.Column('delegated_to_id', sa.String(), nullable=True),
    sa.Column('withdrawer', sa.String(), nullable=False),
    sa.Column('nonce', sa.BigInteger(), nullable=False),
    sa.Column('start_block', sa.BigInteger(), nullable=True),
    sa.Column('strategies', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('shares', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('event_type', sa.Enum('QUEUED', 'COMPLETED', name='withdrawaleventtype'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delegated_to_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staker_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocation_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('magnitude', sa.BigInteger(), nullable=False),
    sa.Column('effect_block', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beacon_chain_deposit_events',
    sa.Column('pod_id', sa.String(), nullable=True),
    sa.Column('pod_owner_id', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['eigen_pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_owner_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beacon_chain_withdrawal_events',
    sa.Column('pod_id', sa.String(), nullable=True),
    sa.Column('pod_owner_id', sa.String(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('nonce', sa.BigInteger(), nullable=False),
    sa.Column('delegated_address', sa.String(), nullable=False),
    sa.Column('withdrawer', sa.String(), nullable=False),
    sa.Column('withdrawal_root', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['eigen_pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_owner_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('burn_or_redistributable_shares_decreased_events',
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('slash_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('burn_or_redistributable_shares_increased_events',
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('slash_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_added_to_operator_set_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_directed_operator_set_rewards_submission_events',
    sa.Column('caller', sa.String(), nullable=False),
    sa.Column('operator_directed_rewards_submission_hash', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('submission_nonce', sa.BigInteger(), nullable=False),
    sa.Column('strategies_and_multipliers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('operator_rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_removed_from_operator_set_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_set_created_events',
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('avs_id', sa.String(), nullable=False),
    sa.Column('operator_set_id_num', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avs_id'], ['avs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_set_split_bips_set_events',
    sa.Column('caller', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('activated_at', sa.BigInteger(), nullable=False),
    sa.Column('old_operator_set_split_bips', sa.BigInteger(), nullable=False),
    sa.Column('new_operator_set_split_bips', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_slashed_events',
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('strategies', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('wad_slashed', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pod_deployed_events',
    sa.Column('pod_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['eigen_pods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pod_shares_update_events',
    sa.Column('pod_id', sa.String(), nullable=True),
    sa.Column('pod_owner_id', sa.String(), nullable=False),
    sa.Column('shares_delta', sa.BigInteger(), nullable=False),
    sa.Column('new_total_shares', sa.BigInteger(), nullable=True),
    sa.Column('update_type', sa.Enum('SHARES_UPDATED', 'NEW_TOTAL_SHARES', name='podsharesupdatetype'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['eigen_pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_owner_id'], ['stakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redistribution_address_set_events',
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('redistribution_recipient', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_operator_set_events',
    sa.Column('operator_set_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('ADDED', 'REMOVED', name='strategyoperatorseteventtype'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_set_id'], ['operator_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_operator_set_events')
    op.drop_table('redistribution_address_set_events')
    op.drop_table('pod_shares_update_events')
    op.drop_table('pod_deployed_events')
    op.drop_table('operator_slashed_events')
    op.drop_table('operator_set_split_bips_set_events')
    op.drop_table('operator_set_created_events')
    op.drop_table('operator_removed_from_operator_set_events')
    op.drop_table('operator_directed_operator_set_rewards_submission_events')
    op.drop_table('operator_added_to_operator_set_events')
    op.drop_table('burn_or_redistributable_shares_increased_events')
    op.drop_table('burn_or_redistributable_shares_decreased_events')
    op.drop_table('beacon_chain_withdrawal_events')
    op.drop_table('beacon_chain_deposit_events')
    op.drop_table('allocation_events')
    op.drop_table('withdrawal_events')
    op.drop_table('strategy_whitelist_events')
    op.drop_table('staker_force_undelegated_events')
    op.drop_table('staker_delegation_events')
    op.drop_table('rewards_submission_events')
    op.drop_table('operator_shares_slashed_events')
    op.drop_table('operator_share_events')
    op.drop_table('operator_sets')
    op.drop_table('operator_registered_events')
    op.drop_table('operator_pi_split_bips_set_events')
    op.drop_table('operator_metadata_update_events')
    op.drop_table('operator_directed_avs_rewards_submission_events')
    op.drop_table('operator_avs_split_bips_set_events')
    op.drop_table('operator_avs_registration_status_updated_events')
    op.drop_table('max_magnitude_updated_events')
    op.drop_table('encumbered_magnitude_updated_events')
    op.drop_table('eigen_pods')
    op.drop_table('deposit_scaling_factor_updated_events')
    op.drop_table('deposit_events')
    op.drop_table('delegation_approver_updated_events')
    op.drop_table('burnable_shares_decreased_events')
    op.drop_table('beacon_chain_slashing_events')
    op.drop_table('beacon_chain_eth_withdrawal_completed_events')
    op.drop_table('avs_registrar_set_events')
    op.drop_table('avs_metadata_update_events')
    op.drop_table('allocation_delay_set_events')
    op.drop_table('strategy_whitelister_changed_events')
    op.drop_table('strategies')
    op.drop_table('stakers')
    op.drop_table('rewards_updater_set_events')
    op.drop_table('rewards_for_all_submitter_set_events')
    op.drop_table('rewards_claimed_events')
    op.drop_table('proof_timestamp_setter_set_events')
    op.drop_table('pectra_fork_timestamp_set_events')
    op.drop_table('operators')
    op.drop_table('distribution_root_submitted_events')
    op.drop_table('distribution_root_disabled_events')
    op.drop_table('default_operator_split_bips_set_events')
    op.drop_table('claimer_for_set_events')
    op.drop_table('burnable_eth_shares_increased_events')
    op.drop_table('avs')
    op.drop_table('activation_delay_set_events')
    # ### end Alembic commands ###
