# models/__init__.py
from .base import Base, TimestampMixin

# Import ALL models to register them with Base.metadata
from .entities import Operator, Staker, AVS, Strategy, OperatorSet, EigenPod
from .events import (
    OperatorRegistered,
    DelegationApproverUpdated,
    OperatorMetadataUpdate,
    OperatorShareEvent,
    StakerDelegationEvent,
    StakerForceUndelegated,
    DepositScalingFactorUpdated,
    WithdrawalEvent,
    OperatorSharesSlashed,
    AllocationDelaySet,
    AllocationEvent,
    EncumberedMagnitudeUpdated,
    MaxMagnitudeUpdated,
    OperatorSlashed,
    AVSRegistrarSet,
    AVSMetadataUpdate,
    OperatorSetCreated,
    OperatorAddedToOperatorSet,
    OperatorRemovedFromOperatorSet,
    RedistributionAddressSet,
    StrategyOperatorSetEvent,
    RewardsSubmission,
    OperatorDirectedAVSRewardsSubmission,
    OperatorDirectedOperatorSetRewardsSubmission,
    RewardsUpdaterSet,
    RewardsForAllSubmitterSet,
    ActivationDelaySet,
    DefaultOperatorSplitBipsSet,
    OperatorAVSSplitBipsSet,
    OperatorPISplitBipsSet,
    OperatorSetSplitBipsSet,
    ClaimerForSet,
    DistributionRootSubmitted,
    DistributionRootDisabled,
    RewardsClaimed,
    Deposit,
    StrategyWhitelisterChanged,
    StrategyWhitelistEvent,
    BurnOrRedistributableSharesIncreased,
    BurnOrRedistributableSharesDecreased,
    BurnableSharesDecreased,
    OperatorAVSRegistrationStatusUpdated,
    PodDeployed,
    BeaconChainDeposit,
    PodSharesUpdate,
    BeaconChainWithdrawal,
    BeaconChainETHWithdrawalCompleted,
    BeaconChainSlashingEvent,
    BurnableETHSharesIncreased,
    PectraForkTimestampSet,
    ProofTimestampSetterSet,
)

__all__ = [
    "Base",
    "TimestampMixin",
    "Operator",
    "Staker",
    "AVS",
    "Strategy",
    "OperatorSet",
    "EigenPod",
] + [cls.__name__ for cls in Base.__subclasses__()]
